[phases.setup]
nixPkgs = ["python39", "pip", "python39Packages.pip"]

[phases.install]
cmds = [
  "python3 -m ensurepip --upgrade",
  "python3 -m pip install --upgrade pip",
  "python3 -m pip install -r requirements.txt"
]

[phases.build]
cmds = [
  "python3 manage.py collectstatic --noinput"
]

[start]
cmd = "python3 start_server.py"
