# Generated by Django 5.2.6 on 2025-09-10 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FoodItem",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("category", models.CharField(max_length=50)),
                ("calories", models.IntegerField()),
                ("serving", models.CharField(max_length=50)),
                ("protein", models.FloatField()),
                ("carbs", models.FloatField()),
                ("fat", models.FloatField()),
                ("fiber", models.FloatField()),
                ("virya", models.CharField(max_length=20)),
                ("digestion", models.CharField(max_length=20)),
                ("rasa", models.CharField(max_length=20)),
                ("guna", models.CharField(max_length=20)),
                ("vata_effect", models.CharField(max_length=5)),
                ("pitta_effect", models.CharField(max_length=5)),
                ("kapha_effect", models.CharField(max_length=5)),
                ("season", models.JSONField(default=list)),
                ("benefits", models.JSONField(default=list)),
                ("precautions", models.JSONField(default=list)),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("age", models.IntegerField()),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("height", models.FloatField(blank=True, null=True)),
                ("weight", models.FloatField(blank=True, null=True)),
                ("bmi", models.FloatField(blank=True, null=True)),
                ("prakriti", models.CharField(blank=True, max_length=50)),
                ("diet", models.CharField(default="Vegetarian", max_length=50)),
                ("meal_frequency", models.IntegerField(default=3)),
                ("water_intake", models.FloatField(default=2.5)),
                ("activity_level", models.CharField(default="Moderate", max_length=20)),
                ("bowel_movement", models.CharField(default="Regular", max_length=20)),
                ("sleep_hours", models.IntegerField(default=7)),
                ("stress_level", models.CharField(default="Medium", max_length=20)),
                ("medical_history", models.TextField(blank=True)),
                ("current_medications", models.TextField(blank=True)),
                ("allergies", models.TextField(blank=True)),
                ("occupation", models.CharField(blank=True, max_length=100)),
                ("exercise_frequency", models.CharField(blank=True, max_length=50)),
                ("last_visit", models.DateField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="DoshaAssessment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=None, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "assessment_type",
                    models.CharField(default="comprehensive", max_length=20),
                ),
                ("responses", models.JSONField()),
                ("primary_dosha", models.CharField(max_length=20)),
                ("dosha_scores", models.JSONField()),
                ("confidence", models.FloatField()),
                ("recommendations", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "patient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="backend.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DietChart",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=None, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("goal", models.CharField(max_length=50)),
                ("target_calories", models.IntegerField()),
                ("duration", models.IntegerField()),
                ("chart_data", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("status", models.CharField(default="Active", max_length=20)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="backend.patient",
                    ),
                ),
            ],
        ),
    ]
